version: '3.8'
services:
  backend:
    build: .
    container_name: backend-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
    restart: unless-stopped
