version: '3.8'
services:
  backend:
    build: .
    container_name: backend-service
    ports:
      - "5000:5000"
    env_file:
      - .env   # <-- This loads the MONGO_URI
    volumes:
      - .:/app
    restart: unless-stopped
